# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-14 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20171014_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(max_length=10200),
        ),
        migrations.AlterField(
            model_name='newswebsite',
            name='url',
            field=models.TextField(),
        ),
    ]
