# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171014_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newswebsite',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newswebsite',
            name='url',
            field=models.CharField(max_length=350),
        ),
    ]
