# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pageweb',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=130),
        ),
    ]
